spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: qa_user
    password: qa_password

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: false
    properties:
      hibernate.format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: API_KEY
      chat:
        options:
          model: gpt-4o-mini

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true